### ISSUE TITLE
Ship 1.0

### ISSUE THREAD

**Issue by vast** [fatezh/fatezh#12]
Todo:
- [x] Google Analytics (done in https://github.com/fatezh/fatezh/commit/7cced5312429089e082c4cbcd7101d54ab622607)
- [x] animate page transitions (done in #11)
- [x] display post author (done in #10)
- [x] add humans.txt (done in https://github.com/fatezh/fatezh/commit/0b459832e7148659a03f2529c3523d35134f085c)
- [x] add latest three articles (done in #16)

/cc @NiyazSerazetdinov

**Comment by NiyazSerazetdinov** [comment]
@vast, I won't be able to open PR with needed articles today. Don't wait for me. Sorry =|

**Comment by vast** [comment]
ok, no worries
